### ISSUE TITLE
\usemhmodule and \guse should generate type "uses" 

### ISSUE THREAD

**Issue by kohlhase** [slatex/lmhtools#1]
There is currently a "include cycle" in the IWGS graph between `editor.tex` and `wordprocessors.tex` but the edge between  `wordprocessors.tex` and `editor.tex` should be a `uses` link. I suspect this is a general problem

I hope that fixing this will reduce cycles and give much better layout

**Comment by jfschaefer** [comment]
Apparently, all edges were include edges so far. I've replaced the edges for `\guse`, `\importmhmodule` etc. with the `"uses"` style.
