### ISSUE TITLE
rename the glossary presentation macros. 

### ISSUE THREAD

**Issue by kohlhase** [slatex/lmhtools#17]
I have moved the glossary presentation macros into `smglom.sty`, this makes dependency struture simpler. I would like to rename them: 
* `smentry` instead of `entry`
* `\smsynonymref` instead of `\synonmymref`
* `\smjointdefref` instead of `\seeref`

**Comment by jfschaefer** [comment]
I've updated the glossary generation code accordingly

**Comment by kohlhase** [comment]
great, works well.
