### ISSUE TITLE
german glossary for IWGS 

### ISSUE THREAD

**Issue by kohlhase** [slatex/lmhtools#18]
please.

**Comment by jfschaefer** [comment]
This should work now. I've also updated the IWGS Makefile to generate `glossary.de.tex`.

**Comment by kohlhase** [comment]
Actually, this uses the English versions (maybe only when the german are not present). That is not really what I want.

**Comment by jfschaefer** [comment]
My mistake, the language check didn't apply to defis mentioned in the lecture itself. this should be fixed now.
