### ISSUE TITLE
the AI graph only has "uses" edges at the moment. 

### ISSUE THREAD

**Issue by kohlhase** [slatex/lmhtools#2]
I just generated it, and the imports are missing.

**Comment by kohlhase** [comment]
It also seems that TGView3D does not recognize the user edges. We should talk to Richard

**Comment by kohlhase** [comment]
this seems to work now. thanks.

**Comment by kohlhase** [comment]
There are still too many uses links. E.G. in IWGS from preorder.tex to transitive.tex. that should be an include link. 
Actually in the graph mode, where we only show theories, I would expect to see few uses links. The mostly occur from text nodes to theories.

**Comment by jfschaefer** [comment]
I think, I need some more clarification here about which edge type should be used when.

In [preoder.tex](https://gl.mathhub.info/smglom/sets/blob/master/source/preorder.tex#L4) there is a `\gimport{transitive}`.

Should `\gimport` and `\importmhmodule` be include edges along with `\mhinputref` and `\input`?
So the uses edges would only come from `\guse` and `\usemhmodule`?

**Comment by kohlhase** [comment]
exactly.

**Comment by jfschaefer** [comment]
This should be fixed now
