### ISSUE TITLE
meta-inf/applications does not generate dictionary files

### ISSUE THREAD

**Issue by kohlhase** [slatex/lmhtools#20]
and I do not know why. *.{en,ro,de,zhs}.tex are missing. 
BTW, I have upated the driver files significantly. We now have to run bibTeX on all of them.

**Comment by jfschaefer** [comment]
I've changed the naming of the dictionary files a bit.

For example, the English -> ... file for the "en-de-ro-zhs" dictionary is called `dictionary.en-de-ro-zhs.en.tex`.

The reasoning is that we would have a different English -> ... file for e.g. an "en-de" dictionary (which would now be called `dictionary.en-de.en.tex`).

**Comment by kohlhase** [comment]
I have corrected the Makefile somewhat, but it is still not working. Could you have a look?

**Comment by kohlhase** [comment]
`make echo` helps.

**Comment by jfschaefer** [comment]
The script generates all the files for a dictionary at once.
I've changed the Makefile a little and introduced a phony target `dictexs-en-de-ro-zhs`, which generates `dictionary.en-de-ro-zhs.*.tex`.

**Comment by kohlhase** [comment]
works for me now.
