### ISSUE TITLE
lemmata with formulae need \usemhmodule (sometimes)

### ISSUE THREAD

**Issue by kohlhase** [slatex/lmhtools#22]
I am starting to generate a glossary for AI. And I get 
```
\begin{smentry}{\hypertarget{x53168c7dca632656}{\guse[MiKoMH/AI]{a-star}$\protect\astarSearch$ search}}{MiKoMH/AI}
\usemhmodule[repos=MiKoMH/AI,path=search/en/a-star]{a-star}
```
in `glossary.en.tex`. This has an error: In line 1, `\guse[MiKoMH/AI]{a-star}` should be  
`\usemhmodule[repos=MiKoMH/AI,path=search/en/a-star]{a-star}`, i.e. just the same as line 3. 
That should always work.

**Comment by jfschaefer** [comment]
That should be fixed now. However, I still get an error in that line due to a missing sms file (which might only be an issue on my machine though).

**Comment by kohlhase** [comment]
> That should be fixed now.

thanks. 

>  I still get an error in that line due to a missing sms file

BTW: `mmt make pdflatex glossary.tex` (tries to) makes  all relevant sms files. That might help.
