### ISSUE TITLE
new form of import/usemhmodule

### ISSUE THREAD

**Issue by kohlhase** [slatex/lmhtools#23]
I have introduced `\importmhmoudle[dir=foo]{bar}` as an abbreviation for `\importmhmodule[path=foo/bar]{bar}` and the same for `\usemhmodule`.
And generally, repos= is now mhrepos=.

I have change the latter in `make_glossary.py`, but I suspect I have not found everything. 

NOTE: the old form is also still valid.

**Comment by jfschaefer** [comment]
I've added support for the `dir` parameter and deprecation warnings if `repos` is used instead of `mhrepos`.
I did some preliminary testing and it seems to work.
