### ISSUE TITLE
expected mtrefi should be amended for drefi

### ISSUE THREAD

**Issue by kohlhase** [slatex/lmhtools#24]
I am getting the error message
```
/Users/kohlhase/localmh/MathHub/MiKoMH/IWGS/source/digdocs/en/trees-cs.tex:11:27: Expected mtrefi for '\drefi[branch?branch]{branches}'
```
but the `\drefi[tree]{root}, \drefi[branch?branch]{branches}, \drefi[tree?leaf]{leaves},` is completely legitimate. 
The error message should not be generated in this case.

**Comment by jfschaefer** [comment]
I think this should be fixed now

**Comment by kohlhase** [comment]
thanks, this works for me now.
